interface FormItem {
  style?: string
  field?: string,
  initialValue?: any,
  rules?: any,
  type?: string,
  el?: (form: JSX.Element) => JSX.Element
  /**
   * Used with label, whether to display : after label text.
   * @default true
   * @type boolean
   */
  colon?: boolean;

  /**
   * The extra prompt message. It is similar to help.
   *  Usage example: to display error message and prompt message at the same time.
   * @type any (string | slot)
   */
  extra?: any;

  /**
   * Used with validateStatus, this option specifies the validation status icon. Recommended to be used only with Input.
   * @default false
   * @type boolean
   */
  hasFeedback?: boolean;

  /**
   * The prompt message. If not provided, the prompt message will be generated by the validation rule.
   * @type any (string | slot)
   */
  help?: any;

  /**
   * Label test
   * @type any (string | slot)
   */
  label?: any;

  /**
   * The layout of label. You can set span offset to something
   * like {span: 3, offset: 12} or sm: {span: 3, offset: 12} same as with <Col>
   * @type Col
   */
  labelCol?: any;

  /**
   * Whether provided or not, it will be generated by the validation rule.
   * @default false
   * @type boolean
   */
  required?: boolean;

  /**
   * The validation status. If not provided,
   *  it will be generated by validation rule. options: 'success' 'warning' 'error' 'validating'
   * @type string
   */
  validateStatus?: '' | 'success' | 'warning' | 'error' | 'validating';

  /**
   * The layout for input controls, same as labelCol
   * @type Col
   */
  wrapperCol?: any;
}

interface IFormProps {
  layout?: 'horizontal' | 'inline' | 'vertical'
  formItems?: FormItem[]
  labelCol?: any
  wrapperCol?: any
  iStyle?: string
  col?: any
}
